# Generic supply chain:  yaml file for
# - 2 services exposing frontend application and backend:  frontend-service und backend-service
# - Deployment for deploying the frontend and backend container
# - Service to expose frontend application

# Dependencies:
kind: Service
apiVersion: v1
metadata:
  name: frontend-service
spec:
  selector:
    name: frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
---
#  Dependencies:
kind: Service
apiVersion: v1
metadata:
  name: backend-service
spec:
  selector:
    name: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
#  Yaml for deployment of backend node.js server and frontend angular app
#  2 containers:  backend = container for backend-api
#                 frontend = container for frontend angular-app
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: backend
    spec:
      containers:
        - name: backend
          # image: us.icr.io/customer_success/backend-gensupplychain:1
          image: registry.ng.bluemix.net/<repo>/<image:version>
          ports:
            - containerPort: 3000
          env:
            - name: PLATFORM
              value: "IBP"
        - name: frontend
          # image: us.icr.io/customer_success/frontend-gensupplychain:1
          image: registry.ng.bluemix.net/<repo>/<image:version>
          ports:
            - containerPort: 4200
